package com.revolution.robotics.core.eventBus.dialog

import android.os.Bundle

enum class DialogEvent {
    PERMISSION_GRANTED,
    BRAIN_TURNED_ON,
    BRAIN_NOT_TURNED_ON,
    ROBOT_CONNECTED,
    ROBOT_CONNECTION_FAILED,
    ROBOT_RECONNECT,
    CHAPTER_FINISHED,
    SKIP_TESTING,
    TEST_WORKS,
    DELETE_ROBOT,
    SAVE_ROBOT,
    ADD_PROGRAM,
    REMOVE_PROGRAM,
    SAVE_CONTROLLER,
    DELETE_CONTROLLER,
    LETS_DRIVE,
    SHOW_PROGRAM_INFO,
    LOAD_PROGRAM,
    DELETE_PROGRAM,
    EDIT_PROGRAM,
    SAVE_PROGRAM,
    DUPLICATE_ROBOT,
    EDIT_ROBOT,
    OPEN_BUILD_FLOW,
    ROBOT_CREATED,
    ROBOT_CREATE_ERROR,
    PROGRAM_CONFIRM_CLOSE_WITH_SAVE,
    PROGRAM_CONFIRM_CLOSE_WITHOUT_SAVE,
    PROGRAM_CONFIRM_LOAD_WITH_SAVE,
    PROGRAM_CONFIRM_LOAD_WITHOUT_SAVE,
    PROGRAM_CONFIRM_CREATE_NEW_WITH_SAVE,
    PROGRAM_CONFIRM_CREATE_NEW_WITHOUT_SAVE,
    ROBOT_SELECTED,
    ROBOT_IMAGE_CHANGED,
    FIRMWARE_INCOMPATIBLE_UPDATE_LATER,
    DEFAULT_CONTROLLER_CHANGED,
    ROBOT_DOWNLOADED;

    val extras = Bundle()
}
